name: myenv
channels:
    - defaults
dependencies:
    - python=3.11
    - click
    - pandas
    - pip
    - tqdm
    - pip:
        - albumentations
        - timm
        - torchmetrics
        - matplotlib
        - pycocotools
        - pytest
